### ISSUE TITLE
[atomspace] nose tests fail (SegFault)

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#35]
These fail:
```
129 - PythonEvalUTest (SEGFAULT)
130 - PythonUtilitiesUTest (SEGFAULT)
136 - CythonForwardchainer (Failed)
137 - CythonBackwardchainer (Failed)
```

However this one is from [#7](https://github.com/opencog/opencog-nix/issues/7#issuecomment-485289238):
```
ERROR: In procedure apply-smob/1:
In procedure dynamic-link: file: "libexec", message: "file not found"
ABORT: misc-error
```

<details><summary>log</summary>
<p>

```
129/137 Test #129: PythonEvalUTest ..................***Exception: SegFault  0.11 sec
Running cxxtest tests (7 tests)[2019-05-19 23:18:08:132] [DEBUG] [PythonEvalUTest] testRawPythonInitialization()
.[2019-05-19 23:18:08:173] [DEBUG] [PythonEvalUTest] testRawPythonInitialization() DONE
[2019-05-19 23:18:08:173] [DEBUG] [PythonEvalUTest] testRawPythonInitializeWithGetSys()
[2019-05-19 23:18:08:180] [DEBUG]     unit-test Python 'sys.path' is:
[2019-05-19 23:18:08:180] [DEBUG]          0 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:180] [DEBUG]          1 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python37.zip
[2019-05-19 23:18:08:180] [DEBUG]          2 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7
[2019-05-19 23:18:08:180] [DEBUG]          3 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7/lib-dynload
[2019-05-19 23:18:08:180] [DEBUG]          4 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7/site-packages
.[2019-05-19 23:18:08:188] [DEBUG] [PythonEvalUTest] testRawPythonInitializeWithGetSys() DONE
[2019-05-19 23:18:08:188] [DEBUG] [PythonEvalUTest] testGlobalPythonInitializationFinalization()
[2019-05-19 23:18:08:189] [INFO] [global_python_initialize] Start
[2019-05-19 23:18:08:195] [INFO] [global_python_initialize] Adding OpenCog sys.path directories
[2019-05-19 23:18:08:195] [DEBUG] Python 'sys.path' is:
[2019-05-19 23:18:08:195] [DEBUG]      0 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:195] [DEBUG]      1 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python37.zip
[2019-05-19 23:18:08:195] [DEBUG]      2 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7
[2019-05-19 23:18:08:195] [DEBUG]      3 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7/lib-dynload
[2019-05-19 23:18:08:195] [DEBUG]      4 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7/site-packages
[2019-05-19 23:18:08:195] [DEBUG]      5 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:195] [DEBUG]      6 > /build/source/tests/cython
[2019-05-19 23:18:08:195] [DEBUG]      7 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:202] [INFO] [global_python_initialize] Finish
[2019-05-19 23:18:08:202] [DEBUG] [global_python_finalize] Start
[2019-05-19 23:18:08:204] [DEBUG] [global_python_finalize] Finish
[2019-05-19 23:18:08:204] [INFO] [global_python_initialize] Start
[2019-05-19 23:18:08:210] [INFO] [global_python_initialize] Adding OpenCog sys.path directories
[2019-05-19 23:18:08:210] [DEBUG] Python 'sys.path' is:
[2019-05-19 23:18:08:210] [DEBUG]      0 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:210] [DEBUG]      1 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python37.zip
[2019-05-19 23:18:08:210] [DEBUG]      2 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7
[2019-05-19 23:18:08:210] [DEBUG]      3 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7/lib-dynload
[2019-05-19 23:18:08:210] [DEBUG]      4 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7/site-packages
[2019-05-19 23:18:08:210] [DEBUG]      5 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:210] [DEBUG]      6 > /build/source/tests/cython
[2019-05-19 23:18:08:210] [DEBUG]      7 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:216] [INFO] [global_python_initialize] Finish
[2019-05-19 23:18:08:216] [DEBUG] [global_python_finalize] Start
.[2019-05-19 23:18:08:218] [DEBUG] [global_python_finalize] Finish
[2019-05-19 23:18:08:218] [DEBUG] [PythonEvalUTest] testGlobalPythonInitializationFinalization() DONE
[2019-05-19 23:18:08:218] [DEBUG] [PythonEvalUTest] testPythonEvalSingletonCreationDeletion()
[2019-05-19 23:18:08:218] [INFO] [global_python_initialize] Start
[2019-05-19 23:18:08:225] [INFO] [global_python_initialize] Adding OpenCog sys.path directories
[2019-05-19 23:18:08:225] [DEBUG] Python 'sys.path' is:
[2019-05-19 23:18:08:225] [DEBUG]      0 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:225] [DEBUG]      1 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python37.zip
[2019-05-19 23:18:08:225] [DEBUG]      2 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7
[2019-05-19 23:18:08:225] [DEBUG]      3 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7/lib-dynload
[2019-05-19 23:18:08:225] [DEBUG]      4 > /nix/store/kpqyl91p6rqi9c1hnkmqjsrphcj1dgha-python3-3.7.3/lib/python3.7/site-packages
[2019-05-19 23:18:08:225] [DEBUG]      5 > /build/source/build/opencog/cython
[2019-05-19 23:18:08:225] [DEBUG]      6 > /build/source/tests/cython
[2019-05-19 23:18:08:225] [DEBUG]      7 > /build/source/build/opencog/cython


        Start 130: PythonUtilitiesUTest
130/137 Test #130: PythonUtilitiesUTest .............***Exception: SegFault  0.05 sec
Running cxxtest tests (1 test)

        Start 131: Cython
131/137 Test #131: Cython ...........................   Passed    1.88 sec
        Start 132: CythonAtomSpace
132/137 Test #132: CythonAtomSpace ..................   Passed    0.33 sec
        Start 133: CythonGuile
133/137 Test #133: CythonGuile ......................   Passed    2.08 sec
        Start 134: CythonUtilities
134/137 Test #134: CythonUtilities ..................   Passed    0.31 sec
        Start 135: CythonBindlink
135/137 Test #135: CythonBindlink ...................   Passed    0.29 sec
        Start 136: CythonForwardchainer
136/137 Test #136: CythonForwardchainer .............***Failed    0.46 sec
test_fc_deduction (test_fc.FCTest) ... ERROR
test_forward_chainer_instantiation (test_fc.FCTest) ... ok

======================================================================
ERROR: test_fc_deduction (test_fc.FCTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/cython/forwardchainer/test_fc.py", line 38, in test_fc_deduction
    scheme_eval(self.atomspace, '(load-from-path "fc-deduction-config.scm")')
  File "scheme_wrapper.pyx", line 44, in opencog.scheme_wrapper.scheme_eval
RuntimeError: Python-Scheme Wrapper: Failed to execute '(load-from-path "fc-deduction-config.scm")'
Backtrace:
In ice-9/boot-9.scm:
  3002:22 19 (_)
In unknown file:
          18 (primitive-load-path "opencog/ure" #<procedure 7fffe9e2…>)
In opencog/scm/opencog/ure.scm:
     11:0 17 (_)
In ice-9/boot-9.scm:
   1693:5 16 (%start-stack load-stack _)
   1695:9 15 (_)
In unknown file:
          14 (primitive-load-path "opencog/ure/ure-utils.scm")
In opencog/scm/opencog/ure/ure-utils.scm:
     70:0 13 (_)
In ice-9/boot-9.scm:
  3365:20 12 (process-use-modules _)
   222:17 11 (map1 (((opencog exec))))
  3366:31 10 (_ ((opencog exec)))
  2788:17  9 (resolve-interface (opencog exec) #:select _ #:hide _ # …)
  2714:10  8 (_ (opencog exec) _ _ #:ensure _)
  2982:16  7 (try-module-autoload _ _)
   2312:4  6 (save-module-excursion #<procedure 7fffe9e459c0 at ice-…>)
  3002:22  5 (_)
In unknown file:
           4 (primitive-load-path "opencog/exec" #<procedure 7fffe9e…>)
In opencog/scm/opencog/exec.scm:
     10:0  3 (_)
In unknown file:
           2 (load-extension "libexec" "opencog_exec_init")
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 misc-error ("dynamic-link" "fi…" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 7fffe9e2e6c0> misc-error # …)

ERROR: In procedure apply-smob/1:
In procedure dynamic-link: file: "libexec", message: "file not found"
ABORT: misc-error
 (/build/source/opencog/cython/opencog/PyScheme.cc:63)

----------------------------------------------------------------------
Ran 2 tests in 0.189s

FAILED (errors=1)

        Start 137: CythonBackwardchainer
137/137 Test #137: CythonBackwardchainer ............***Failed    0.54 sec
port of crisp.scm from examples/ure/simple ... ERROR
Test for correct vardecl parameter initialization in BackwardChainer ... ok

======================================================================
ERROR: port of crisp.scm from examples/ure/simple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/cython/backwardchainer/test_bc.py", line 49, in test_bc_deduction
    scheme_eval(self.atomspace, '(use-modules (opencog exec))')
  File "scheme_wrapper.pyx", line 44, in opencog.scheme_wrapper.scheme_eval
RuntimeError: Python-Scheme Wrapper: Failed to execute '(use-modules (opencog exec))'
Backtrace:
          19 (apply-smob/1 #<catch-closure 7fffe9df85c0>)
In ice-9/boot-9.scm:
   2312:4 18 (save-module-excursion #<procedure 7fffe9df0060 at ice-…>)
In ice-9/eval-string.scm:
     38:6 17 (read-and-eval #<input: string 7fffe9dcf770> #:lang _)
In ice-9/eval.scm:
   721:20 16 (primitive-eval (use-modules (opencog exec)))
In ice-9/psyntax.scm:
  1235:36 15 (expand-top-sequence ((use-modules (opencog exec))) _ _ …)
  1182:24 14 (parse _ (("placeholder" placeholder)) ((top) #(# # …)) …)
   285:10 13 (parse _ (("placeholder" placeholder)) (()) _ c&e (eval) …)
In ice-9/boot-9.scm:
  3365:20 12 (process-use-modules _)
   222:17 11 (map1 (((opencog exec))))
  3366:31 10 (_ ((opencog exec)))
  2788:17  9 (resolve-interface (opencog exec) #:select _ #:hide _ # …)
  2714:10  8 (_ (opencog exec) _ _ #:ensure _)
  2982:16  7 (try-module-autoload _ _)
   2312:4  6 (save-module-excursion #<procedure 7fffe9de9750 at ice-…>)
  3002:22  5 (_)
In unknown file:
           4 (primitive-load-path "opencog/exec" #<procedure 7fffe9d…>)
In opencog/scm/opencog/exec.scm:
     10:0  3 (_)
In unknown file:
           2 (load-extension "libexec" "opencog_exec_init")
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 misc-error ("dynamic-link" "fi…" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 7fffe9df8580> misc-error # …)

ERROR: In procedure apply-smob/1:
In procedure dynamic-link: file: "libexec", message: "file not found"
ABORT: misc-error
 (/build/source/opencog/cython/opencog/PyScheme.cc:63)

----------------------------------------------------------------------
Ran 2 tests in 0.264s

FAILED (errors=1)
Enter test_bc_deduction
test_bc_deduction: pre scheme eval
Item0
small
Item0
large
Item1
small
Item1
large


97% tests passed, 4 tests failed out of 137

Total Test time (real) = 189.24 sec

The following tests FAILED:
        129 - PythonEvalUTest (SEGFAULT)
        130 - PythonUtilitiesUTest (SEGFAULT)
        136 - CythonForwardchainer (Failed)
        137 - CythonBackwardchainer (Failed)
```
</p>
</details>

**Comment by Radivarig** [comment]
Failing `CythonForwardchainer` test no longer exist.
