### ISSUE TITLE
[opencog] OpenPsiCythonTest test_create_rule fails (AssertionError: 2 != 1)

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#52]
Not sure if this is related to #51.

```
test 9
    Start 9: OpenPsiCythonTest

9: Test command: /nix/store/2xyn8d0f2y8dlyn9vgj0ksmb2n52i1k9-python3.6-nose-1.3.7/bin/nosetests "-vs" "/home/radivarig/projects/opencog-dev/source/tests/cython/openpsi/"
9: Environment variables: 
9:  PYTHONPATH=/nix/store/2103m3hmpf0022sxsvrbl98qnajcvbcm-link-grammar/lib/python3.6/site-packages:/nix/store/p9ikwbfdfkp04i4hz00bf4fd0km1vds2-python3-3.6.9/lib/python3.6/site-packages:/nix/store/ba69dp4vxn93q48sbdlc3rrnvm7cm5x2-python3.6-Cython-0.29.5/lib/python3.6/site-packages:/nix/store/d830vgk61jwkqjxp0aynk1q5p8aiakw1-python3.6-setuptools-40.8.0/lib/python3.6/site-packages:/nix/store/2xyn8d0f2y8dlyn9vgj0ksmb2n52i1k9-python3.6-nose-1.3.7/lib/python3.6/site-packages:/nix/store/w3zk7f8kvqrcqgrbqf672g78x1wyim39-python3.6-coverage-4.5.2/lib/python3.6/site-packages:/nix/store/2103m3hmpf0022sxsvrbl98qnajcvbcm-link-grammar/lib/python3.6/site-packages:/nix/store/p9ikwbfdfkp04i4hz00bf4fd0km1vds2-python3-3.6.9/lib/python3.6/site-packages:/nix/store/ba69dp4vxn93q48sbdlc3rrnvm7cm5x2-python3.6-Cython-0.29.5/lib/python3.6/site-packages:/nix/store/d830vgk61jwkqjxp0aynk1q5p8aiakw1-python3.6-setuptools-40.8.0/lib/python3.6/site-packages:/nix/store/2xyn8d0f2y8dlyn9vgj0ksmb2n52i1k9-python3.6-nose-1.3.7/lib/python3.6/site-packages:/nix/store/w3zk7f8kvqrcqgrbqf672g78x1wyim39-python3.6-coverage-4.5.2/lib/python3.6/site-packages:/nix/store/2103m3hmpf0022sxsvrbl98qnajcvbcm-link-grammar/lib/python3.6/site-packages:/nix/store/p9ikwbfdfkp04i4hz00bf4fd0km1vds2-python3-3.6.9/lib/python3.6/site-packages:/nix/store/ba69dp4vxn93q48sbdlc3rrnvm7cm5x2-python3.6-Cython-0.29.5/lib/python3.6/site-packages:/nix/store/d830vgk61jwkqjxp0aynk1q5p8aiakw1-python3.6-setuptools-40.8.0/lib/python3.6/site-packages:/nix/store/2xyn8d0f2y8dlyn9vgj0ksmb2n52i1k9-python3.6-nose-1.3.7/lib/python3.6/site-packages:/nix/store/w3zk7f8kvqrcqgrbqf672g78x1wyim39-python3.6-coverage-4.5.2/lib/python3.6/site-packages:/nix/store/2103m3hmpf0022sxsvrbl98qnajcvbcm-link-grammar/lib/python3.6/site-packages:/nix/store/p9ikwbfdfkp04i4hz00bf4fd0km1vds2-python3-3.6.9/lib/python3.6/site-packages:/nix/store/ba69dp4vxn93q48sbdlc3rrnvm7cm5x2-python3.6-Cython-0.29.5/lib/python3.6/site-packages:/nix/store/d830vgk61jwkqjxp0aynk1q5p8aiakw1-python3.6-setuptools-40.8.0/lib/python3.6/site-packages:/nix/store/2xyn8d0f2y8dlyn9vgj0ksmb2n52i1k9-python3.6-nose-1.3.7/lib/python3.6/site-packages:/nix/store/w3zk7f8kvqrcqgrbqf672g78x1wyim39-python3.6-coverage-4.5.2/lib/python3.6/site-packages:/nix/store/2103m3hmpf0022sxsvrbl98qnajcvbcm-link-grammar/lib/python3.6/site-packages:/nix/store/p9ikwbfdfkp04i4hz00bf4fd0km1vds2-python3-3.6.9/lib/python3.6/site-packages:/nix/store/ba69dp4vxn93q48sbdlc3rrnvm7cm5x2-python3.6-Cython-0.29.5/lib/python3.6/site-packages:/nix/store/d830vgk61jwkqjxp0aynk1q5p8aiakw1-python3.6-setuptools-40.8.0/lib/python3.6/site-packages:/nix/store/2xyn8d0f2y8dlyn9vgj0ksmb2n52i1k9-python3.6-nose-1.3.7/lib/python3.6/site-packages:/nix/store/w3zk7f8kvqrcqgrbqf672g78x1wyim39-python3.6-coverage-4.5.2/lib/python3.6/site-packages::/nix/store/bk2xsf59wdj3n3ji9wzr7bnxgc15scy4-moses/lib:/nix/store/bk2xsf59wdj3n3ji9wzr7bnxgc15scy4-moses/share/python3.6./site-packages:/nix/store/bk2xsf59wdj3n3ji9wzr7bnxgc15scy4-moses/share/python3.6./site-packages/opencog:/nix/store/c35jz30bplvw8q3bqwiq5mzfvpjwh3xl-spacetime/lib:/nix/store/c35jz30bplvw8q3bqwiq5mzfvpjwh3xl-spacetime/lib/opencog:/nix/store/q3ddwlyisgkvdazcjhrnpjcb2af2byqn-cogutil/lib/opencog:/nix/store/hq701bwk2sza5gg1bh2rhdw43j8skcdd-ure/lib/opencog:/nix/store/hq701bwk2sza5gg1bh2rhdw43j8skcdd-ure/share/python3.6/site-packages:/nix/store/hq701bwk2sza5gg1bh2rhdw43j8skcdd-ure/share/python3.6/site-packages/opencog:/nix/store/s79qbbcpgjjhah0rvcffxiv4b9h78h7r-atomspace/lib/opencog:/nix/store/s79qbbcpgjjhah0rvcffxiv4b9h78h7r-atomspace/share/python3.6/site-packages:/nix/store/s79qbbcpgjjhah0rvcffxiv4b9h78h7r-atomspace/share/python3.6/site-packages/opencog:/nix/store/gxvxskjy91d6a3rzj8xca0ij6jn5r3yg-cogserver/lib/opencog:/nix/store/gxvxskjy91d6a3rzj8xca0ij6jn5r3yg-cogserver/lib/opencog/modules:/nix/store/gxvxskjy91d6a3rzj8xca0ij6jn5r3yg-cogserver/share/python3.6/site-packages:/nix/store/gxvxskjy91d6a3rzj8xca0ij6jn5r3yg-cogserver/share/python3.6/site-packages/opencog:/nix/store/c35jz30bplvw8q3bqwiq5mzfvpjwh3xl-spacetime/lib:/nix/store/c35jz30bplvw8q3bqwiq5mzfvpjwh3xl-spacetime/lib/opencog:/nix/store/n65lwxsi947j95ssd02c587dq9yadbra-attention/lib/opencog:/nix/store/n65lwxsi947j95ssd02c587dq9yadbra-attention/lib/opencog/modules:/nix/store/n65lwxsi947j95ssd02c587dq9yadbra-attention/share/python3.6/site-packages:/nix/store/n65lwxsi947j95ssd02c587dq9yadbra-attention/share/python3.6/site-packages/opencog:/nix/store/47qv9p1ayfizvmvxz0jjb402rn3v48zc-octomap/lib:/home/radivarig/projects/opencog-dev/source/build/opencog/cython:/home/radivarig/projects/opencog-dev/source/build/opencog/openpsi:share/python3.6/site-packages
9: Test timeout computed to be: 10000000
9: test_create_rule (openpsi_test.OpenPsiTest) ... FAIL
9: test_run_openpsi (openpsi_test.OpenPsiTest) ... SKIP: Issue https://github.com/opencog/opencog/issues/3532
9: 
9: ======================================================================
9: FAIL: test_create_rule (openpsi_test.OpenPsiTest)
9: ----------------------------------------------------------------------
9: Traceback (most recent call last):
9:   File "/home/radivarig/projects/opencog-dev/source/tests/cython/openpsi/openpsi_test.py", line 68, in test_create_rule
9:     self.assertEqual(2, len(categories))
9: AssertionError: 2 != 1
9: 
9: ----------------------------------------------------------------------
9: Ran 2 tests in 0.086s
9: 
9: FAILED (SKIP=1, failures=1)
9: duuuude its cat= [(ConceptNode "test-component") ; [8006027917101467350][1]]
9/9 Test #9: OpenPsiCythonTest ................***Failed    0.39 sec
test_create_rule (openpsi_test.OpenPsiTest) ... FAIL
test_run_openpsi (openpsi_test.OpenPsiTest) ... SKIP: Issue https://github.com/opencog/opencog/issues/3532

======================================================================
FAIL: test_create_rule (openpsi_test.OpenPsiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/radivarig/projects/opencog-dev/source/tests/cython/openpsi/openpsi_test.py", line 68, in test_create_rule
    self.assertEqual(2, len(categories))
AssertionError: 2 != 1

----------------------------------------------------------------------
Ran 2 tests in 0.086s

FAILED (SKIP=1, failures=1)
duuuude its cat= [(ConceptNode "test-component") ; [8006027917101467350][1]]


89% tests passed, 1 tests failed out of 9

Total Test time (real) =  90.16 sec

The following tests FAILED:
	  9 - OpenPsiCythonTest (Failed)
Errors while running CTest
make[3]: *** [CMakeFiles/test.dir/build.make:58: CMakeFiles/test] Error 8
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/test.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/test.dir/rule] Error 2
make: *** [Makefile:186: test] Error 2
```

**Comment by linas** [comment]
Argh.  Unmaintained software. It passes on my machine, but as of earlier today, all four openpsi unit tests fail on the circle-ci test of atomspace, but all four pass on the circle-ci-test of opencog itself.  Which suggests something screwy with the circle-ci environment. 

I'm getting frustrated by these random unit test failures.

**Comment by Radivarig** [comment]
I either didn't include some folders or wasn't properly patching the source codes `CMakeLists.txt`s regarding `PYTHONPATH` so I went to complete #45 to fix both.

And this no longer happens! Overall I should've done it much sooner but it kept seeming like it was 1 folder away from working.. 

Not sure about circle-ci, but I am couple of commits behind on `atompace` and `opencog`, as there are some fresh errors similar to #50 that I will report after a bit of C research.

#51 still does happen so they seem not related, but since the test is not breaking I just left it there.
